ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE USER THUEXE IDENTIFIED BY 123456;

GRANT CONNECT, RESOURCE TO THUEXE;

GRANT CREATE VIEW TO THUEXE;
GRANT CREATE TRIGGER TO THUEXE;
GRANT CREATE SEQUENCE TO THUEXE;
GRANT CREATE PROCEDURE TO THUEXE;